### PR TITLE
lock all dependencies

### LINKED ISSUE #8: Server doesn't start
Error from the LSP logs (immediately after initialize request):
```
LSP-ruff: Traceback (most recent call last):
LSP-ruff:   File "<frozen runpy>", line 198, in _run_module_as_main
LSP-ruff:   File "<frozen runpy>", line 88, in _run_code
LSP-ruff:   File "C:\Users\jwortmann\AppData\Local\Sublime Text\Package Storage\LSP-ruff\Scripts\ruff-lsp.exe\__main__.py", line 7, in <module>
LSP-ruff:   File "C:\Users\jwortmann\AppData\Local\Sublime Text\Package Storage\LSP-ruff\Lib\site-packages\ruff_lsp\__main__.py", line 5, in main
LSP-ruff:     from ruff_lsp import __version__, server
LSP-ruff:   File "C:\Users\jwortmann\AppData\Local\Sublime Text\Package Storage\LSP-ruff\Lib\site-packages\ruff_lsp\server.py", line 52, in <module>
LSP-ruff:     from pygls import protocol, server, uris, workspace
LSP-ruff:   File "C:\Users\jwortmann\AppData\Local\Sublime Text\Package Storage\LSP-ruff\Lib\site-packages\pygls\protocol.py", line 56, in <module>
LSP-ruff:     from lsprotocol.types import (
LSP-ruff: ImportError: cannot import name 'WorkspaceConfigurationParams' from 'lsprotocol.types' (C:\Users\jwortmann\AppData\Local\Sublime Text\Package Storage\LSP-ruff\Lib\site-packages\lsprotocol\types.py)
```

I've checked the file from the error message and `WorkspaceConfigurationParams` indeed doesn't exist in that file.

Windows 11

### PR DESCRIPTION
**Pull request by rchl**
Fixes #8

### CODE REVIEW

**Comment by LDAP** [comment]
Not sure if we should fix that here since there is already a new release of ruff-lsp with a patch https://github.com/charliermarsh/ruff-lsp/pull/79

**Comment by rchl** [comment]
It's not as much a fix for #8 but more just a good practice of locking all dependencies. I think we should do that regardless of what did ruff-lsp did to fix the issue.

**Review by LDAP — APPROVED** [review]
No issue on Linux. We could bump ruff-lsp to 0.0.20 while we're at it.

**Comment by rchl** [comment]
Dependabot should create a PR automatically after this is merged.
It would be a good first test that bumping works.

**Comment by rchl** [comment]
I guess we'll have to wait a little bit more for the dependabot.

**Comment by LDAP** [comment]
I triggered the bot manually. The results should show up in a moment.

**Pull request merged**
